// Node types.
export const COMPOUND = 1
export const IDENTIFIER = 2
export const LITERAL = 3
export const PROPERTY = 4
// Node expression types.
export const ARRAY_EXPRESSION = 5
export const ASSIGN_EXPRESSION = 6
export const BINARY_EXPRESSION = 7
export const CALL_EXPRESSION = 8
export const CONDITION_EXPRESSION = 9
export const MEMBER_EXPRESSION = 10
export const OBJECT_EXPRESSION = 11
export const SEQUENCE_EXPRESSION = 12
export const UNARY_EXPRESSION = 13
export const UPDATE_EXPRESSION = 14

export default {
  COMPOUND: COMPOUND,
  IDENTIFIER: IDENTIFIER,
  LITERAL: LITERAL,
  PROPERTY: PROPERTY,

  ARRAY_EXPRESSION: ARRAY_EXPRESSION,
  ASSIGN_EXPRESSION: ASSIGN_EXPRESSION,
  BINARY_EXPRESSION: BINARY_EXPRESSION,
  CALL_EXPRESSION: CALL_EXPRESSION,
  CONDITION_EXPRESSION: CONDITION_EXPRESSION,
  MEMBER_EXPRESSION: MEMBER_EXPRESSION,
  OBJECT_EXPRESSION: OBJECT_EXPRESSION,
  SEQUENCE_EXPRESSION: SEQUENCE_EXPRESSION,
  UNARY_EXPRESSION: UNARY_EXPRESSION,
  UPDATE_EXPRESSION: UPDATE_EXPRESSION,
}
